## Data Cleaning

Techniques for cleaning & preparing data

### Learning Outcomes
- how to find & fix missing values
- how to simplify your data
- how to fix data-type problems
- how to work with indexes

In [9]:
!pip install pandas numpy seaborn matplotlib

Requirement already satisfied: pandas in ./.venv/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy in ./.venv/lib/python3.10/site-packages (2.2.6)
Requirement already satisfied: seaborn in ./.venv/lib/python3.10/site-packages (0.13.2)
Requirement already satisfied: matplotlib in ./.venv/lib/python3.10/site-packages (3.10.8)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.10/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.10/site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.10/site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.10/site-packages (from matplotlib) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.10/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.10/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.10/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.10/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv("ODF_Fire_Data.csv")

In [12]:

df.describe(include="all")

,Serial,FireCategory,FireYear,Area,DistrictName,UnitName,FullFireNumber,FireName,Size_class,EstTotalAcres,...,Industrial_Restriction,Ign_DateTime,ReportDateTime,Discover_DateTime,Control_DateTime,CreationDate,ModifiedDate,DistrictCode,UnitCode,DistFireNumber
count,23490.000000,23490,23490.00000,23490,23490,23490,23490,23490,23490,23411.000000,...,23401,23396,23490,23396,23395,23487,23490,23490.000000,23490.000000,23490
unique,NaN,1,NaN,3,14,31,23335,19637,7,NaN,...,7,20257,22822,22504,22304,11005,22865,NaN,NaN,1009
top,NaN,STAT,NaN,SOA,Southwest Oregon,Grants Pass,02-952017-03,Mill Creek,A,NaN,...,Does Not Apply - Eastern OR,07/15/2018 09:00:00 AM,08/17/2022 05:00:00 PM,08/17/2022 05:00:00 PM,12/31/2013 12:00:00 PM,08/19/2008 12:00:00 AM,10/26/2001 10:20:00 AM,NaN,NaN,018
freq,NaN,23490,NaN,12125,5975,3072,2,33,17013,NaN,...,6562,92,18,19,20,67,12,NaN,NaN,257
mean,90425.933461,NaN,2010.80132,NaN,NaN,NaN,NaN,NaN,NaN,270.802503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.754662,779.371052,NaN
std,20901.016028,NaN,6.73508,NaN,NaN,NaN,NaN,NaN,NaN,6816.736966,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.618857,146.534574,NaN
min,57485.000000,NaN,2000.00000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.000000,511.000000,NaN
25%,72508.500000,NaN,2005.00000,NaN,NaN,NaN,NaN,NaN,NaN,0.010000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.000000,711.000000,NaN
50%,88340.000000,NaN,2011.00000,NaN,NaN,NaN,NaN,NaN,NaN,0.100000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.000000,732.000000,NaN
75%,107432.500000,NaN,2017.00000,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.000000,954.000000,NaN
max,134021.000000,NaN,2022.00000,NaN,NaN,NaN,NaN,NaN,NaN,499945.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.000000,991.000000,NaN

## Renaming Messy Columns

Convention says:

- Column names should be lowercase.
- Whitespace should be replaced with underscores (snake_case).

In [13]:
df_columns_renamed= df.rename(columns = {
  "Serial": "serial_id",
    "FireCategory": "fire_category",
    "FireYear": "fire_year",
    "Area": "area_name",
    "DistrictName": "district_name",
    "UnitName": "unit_name",
    "FullFireNumber": "full_fire_number",
    "FireName": "fire_name",
    "EstTotalAcres": "estimated_total_acres",
    "ReportDateTime": "report_datetime",
    "CreationDate": "created_at",
    "ModifiedDate": "modified_at",
    "DistrictCode": "district_code",
    "UnitCode": "unit_code",
    "DistFireNumber": "district_fire_number"
})

df.columns = df_columns_renamed.columns.str.lstrip().str.rstrip().str.replace(" ", "_").str.lower()

In [14]:
df.head()

,serial_id,fire_category,fire_year,area_name,district_name,unit_name,full_fire_number,fire_name,size_class,estimated_total_acres,...,industrial_restriction,ign_datetime,report_datetime,discover_datetime,control_datetime,created_at,modified_at,district_code,unit_code,district_fire_number
0,102649,STAT,2015,EOA,Klamath-Lake,Klamath,15-981082-16,Bass 497,B,3.20,...,Does Not Apply - Eastern OR,09/02/2015 05:00:00 PM,09/02/2015 05:05:00 PM,09/02/2015 05:00:00 PM,09/02/2015 11:00:00 PM,09/05/2015 12:00:00 AM,10/13/2015 08:39:00 AM,98,981,082
1,131239,STAT,2022,EOA,Walker Range - WRFPA,Crescent,22-991220-23,Hay Fire,A,NaN,...,NaN,NaN,08/16/2022 06:56:00 PM,NaN,NaN,08/18/2022 12:00:00 AM,08/18/2022 09:11:00 AM,99,991,220
2,58256,STAT,2000,EOA,Central Oregon,John Day,00-952011-01,Slick Ear #2,B,0.75,...,Does Not Apply - Eastern OR,07/18/2000 07:00:00 PM,07/19/2000 01:20:00 PM,07/19/2000 01:15:00 PM,07/20/2000 12:50:00 AM,07/20/2000 09:13:00 AM,11/14/2000 09:16:00 AM,95,952,011
3,59312,STAT,2000,EOA,Northeast Oregon,La Grande,00-971024-01,Woodley,C,80.00,...,Does Not Apply - Eastern OR,08/24/2000 05:30:00 AM,08/24/2000 01:07:00 PM,08/24/2000 01:07:00 PM,09/01/2000 09:30:00 PM,08/29/2000 03:59:00 PM,12/21/2000 04:22:00 PM,97,971,024
4,61657,STAT,2001,SOA,Southwest Oregon,Grants Pass,01-712133-02,QUEENS BRANCH,A,0.10,...,Lvl 3 Restricted Shutdown,08/10/2001 05:40:00 PM,08/10/2001 05:47:00 PM,08/10/2001 05:45:00 PM,08/10/2001 06:30:00 PM,08/10/2001 06:42:00 PM,08/17/2001 11:45:00 AM,71,712,133

In [15]:
df.isna().sum().sum()

np.int64(16012)

## Removing NaN

For the most part, removing NaN values is a good thing because it removes missing data that impacts your analysis.

You must decide whether you are:
- Removing an entire row if it contains a NaN
- Removing columns that contain a large amount of NaN values
- Remove only rows or columns that are completely NaN
Consider
- The amount of data lost
- Does the missing data have meaning
- Should you fill the NaN instead of removing the row completely

In [16]:
print(df.shape)
df = df.dropna(how="all", axis="columns")
df = df.dropna(how="all")
df = df.drop(columns=["cause_comments"])
print(df.isna().sum().sort_values(ascending=False))

(23490, 38)
landmarklocation          1282
specificcause              224
causeby                    128
control_datetime            95
ign_datetime                94
discover_datetime           94
industrial_restriction      89
reguserestriction           89
estimated_total_acres       79
regusezone                  50
subdiv                      31
rng                         15
twn                         12
sec                         12
latlongdd                   10
long_dd                     10
lat_dd                      10
created_at                   3
serial_id                    0
fire_year                    0
fire_category                0
district_name                0
area_name                    0
unit_name                    0
full_fire_number             0
size_class                   0
fire_name                    0
protected_acres              0
humanorlightning             0
fo_landowntype               0
generalcause                 0
county                       0
report_datetime              0
modified_at                  0
district_code                0
unit_code                    0
district_fire_number         0
dtype: int64

In [17]:
df["specificcause"].unique()

array([nan, 'Lightning', 'Other - Smoker Related', 'Fireworks',
       'Other - Burning Related', 'Powerlines - prior to 2017',
       'Other - Miscellaneous Related', 'Other - Arson Related',
       'Hot Ashes (Dumping of)', 'Warming Fire',
       'Carbon Sparks from Vehicle', 'Burning Vehicle or Equipment',
       'Rubbish Disposal', 'Discarded Cigarette/Tobacco',
       'Firearms - General', 'Other - Recreationist Related',
       'Unattended', 'Inadequate Mop Up', 'Burning During Poor Condition',
       'Inadequate Resources to Control',
       'Other -Equipment Use Related (ie. road const., other i.c.e.)',
       'Industrial- Rotary Saw - Sparks or Friction',
       'Campfire Not Extinguished', 'Warming Fire Not Extinguished',
       'Burning Building', 'Sparks from Farm Machinery',
       'Inadequate clearing', 'Industrial- Cable System',
       'Cutting, Welding, or Grinding',
       'Playing With Fire (Juveniles 12 years and under)',
       'Landowner Electrical Service',
       'Industrial- Exhaust or Spark - Truck',
       'Industrial- Slash-Holdover Prev. Burn(>90 days after ign.)',
       'Electric Fence', 'Using Fireworks (Juveniles 12 years and under)',
       'Caused due to Emotional Dysfunction/Distress',
       'Smoker Dropped Burning Match',
       'Industrial- Slash-Other Slash Disposal After Burn',
       'Industrial- Slash-Improper Ignition Sequence',
       'Heat from Vehicle Manifold or Exhaust',
       'Industrial- Slash-Failure to Adequately Mop Up',
       'Burning Prohibited Material (rubber, plastic, etc.See Manual',
       'Warming Fire Unattended', 'Failure to Follow Permit Instruction',
       'Industrial- Slash-Other Slash Disposal Fires During Burn',
       'Malfunction of Camp Appliance Fuel (Lantern,etc)',
       'Industrial- Slash-Failure to Adequately Patrol',
       'Industrial- Electrical Wiring on Equipment',
       'Industrial- Welding, Cutting, or Grinding',
       'Spontaneous Combustion', 'Using Fireworks (Juv. ages 13 to 17)',
       'Industrial- Power Saw', 'Burn Barrel',
       'Industrial- Rigging - Sparks or Friction',
       'Fire to Cover-up/Distract from Criminal Act',
       'Track Maintenance (Welding & Grinding)',
       'Other (Juveniles 12 years and under)',
       'Industrial- Slash-Failure to Recog. Sev. of Burning Cond.',
       'Fire to Cause Damage/Injury to Public Agency',
       'Criminal Mischief (Juveniles 12 and under)',
       'Industrial- Other - Logging Equipment Use',
       'Other - Railroad Related',
       'Playing With Fire (Juveniles ages 13 to 17)',
       'Other (Juveniles ages 13 to 17)',
       'Campfire Left Unattended (camp site, cooking)',
       'Industrial- Slash-Fire Line Not Adq. (Inc. Foam Burn Line)',
       'Criminal Mischief (Juv. ages 13 to 17)',
       'Industrial- Exhaust or Spark - Tractor', 'Insect & Pest Control',
       'Industrial- Slash-Insufficient Manpower & Equipment',
       'Engine Exhaust', 'Power Saw (Not in Forest Operation)', 'Hot Box',
       'Industrial- Slash-Failure to Follow Burn Permit Instructions',
       'Industrial- Slash-Failure to Construct Adequate Fire Break',
       'Reckless Burning (13 to 17)', 'Brakeshoe', 'Explosive Device',
       'Smoking (Juveniles 12 years and under)',
       'Industrial- Exhaust or Spark - Mobile Loader',
       'Ignition of Appliance Fuel',
       'Fire to Cause Damage/Injury to Person',
       'Reckless Burning (Juv. 12 and under)',
       'Smoking (Juveniles ages 13 to 17)', 'Warming Fire - Industrial',
       'Industrial- Blasting', 'Fire for Profit or Opportunity',
       'Smoke chase thought to be lightning', 'Creation of Hunting Area',
       'Aircraft', 'Flares', 'Right-of-way Clearing', 'Emptied Ash Tray',
       'Willfull (Juveniles 12 and under)', 'Sparks from House Chimney',
       'Other non-fire summaries',
       'Industrial- Exhaust of Spark - Stationary Engine',
       'Debris Burning (Ties, Bridge Material, etc.)',
       'Firearms - Ammunition', 'Charcoal use or disposal',
       'Powerlines - Power pole malfunction (transformer, fuse, etc.',
       'Powerlines - Tree/branch outside right of way',
       'Powerlines - Animal', 'Powerlines - Other',
       'Powerlines - Tree/branch within right of way',
       'Powerlines - Weather', 'Mowing - Residential',
       'Mowing - Roadside', 'Agricultural', 'Agriculture',
       'Powerlines - Vehicle into power lines',
       'Powerlines - Vehicle into power pole', 'Mowing - Agriculture',
       'Firearms - Target', 'Industrial- Log Friction While Yarding',
       'Blasting', 'Worker Smoking', 'Willfull (Juv. ages 13 to 17)'],
      dtype=object)

In [18]:
df["causeby"].unique()

array(['Other-Public', nan, 'Lightning', 'Motorist', 'Public Utility',
       'Recreationist', 'Ruralist-Paying', 'Hunter',
       'Other-Landowner Related', 'Transient', 'Other Forest Mgt. Worker',
       'Rancher-Farmer', 'Timber Harvest Worker', 'Ruralist-Non-Paying',
       'Hiker', 'Fisherman', 'Marijuana Grower'], dtype=object)

In [19]:
df["specificcause"] = df["specificcause"].fillna("unknown")
df["causeby"] = df["causeby"].fillna("unknown")
print(df.isna().sum().sort_values(ascending=False))

landmarklocation          1282
control_datetime            95
ign_datetime                94
discover_datetime           94
industrial_restriction      89
reguserestriction           89
estimated_total_acres       79
regusezone                  50
subdiv                      31
rng                         15
twn                         12
sec                         12
lat_dd                      10
long_dd                     10
latlongdd                   10
created_at                   3
district_name                0
serial_id                    0
area_name                    0
fire_year                    0
fire_category                0
fo_landowntype               0
generalcause                 0
specificcause                0
full_fire_number             0
size_class                   0
protected_acres              0
humanorlightning             0
causeby                      0
unit_name                    0
fire_name                    0
county                       0
report_datetime              0
modified_at                  0
district_code                0
unit_code                    0
district_fire_number         0
dtype: int64

In [20]:
df = df.dropna()
df.shape

(22092, 37)

## Your Turn: Remove NaN from Your Data

1. Investigate how many NaN values exist in each column.
2. Decide whether you will drop the column, replace the NaN values, or drop the rows containing NaN.
3. Update your dataset so that it contains no remaining NaN values.

## Updating Dates

You must convert your dates from strings into datetime objects.  
This allows you to use built-in date methods and perform time-based calculations.

In [21]:
df["ign_datetime"].head(20)
df["discover_datetime"].head(20)
df["control_datetime"].head(20)
df["report_datetime"].head(20)

0     09/02/2015 05:05:00 PM
2     07/19/2000 01:20:00 PM
3     08/24/2000 01:07:00 PM
4     08/10/2001 05:47:00 PM
6     07/06/2002 01:04:00 PM
7     08/22/2003 05:00:00 AM
8     08/23/2003 09:24:00 AM
9     08/30/2003 02:37:00 PM
10    09/18/2005 03:20:00 PM
11    08/26/2005 11:29:00 PM
12    06/23/2007 05:47:00 PM
13    08/25/2014 01:15:00 PM
15    10/26/2008 12:01:00 PM
16    08/17/2008 09:15:00 PM
18    09/03/2009 03:40:00 PM
19    08/01/2009 07:59:00 PM
21    08/17/2009 11:52:00 AM
22    07/15/2009 05:30:00 AM
24    07/06/2010 08:50:00 PM
25    07/09/2010 11:53:00 AM
Name: report_datetime, dtype: object

In [22]:
date_columns = [
    "ign_datetime",
    "discover_datetime",
    "control_datetime",
    "report_datetime"
]

for column in date_columns:
    df[column] = pd.to_datetime(
        df[column],
        format="%Y/%m/%d %H:%M:%S %p",
        errors="coerce"
    )
df[[
    "ign_datetime",
    "discover_datetime",
    "control_datetime",
    "report_datetime"
]].dtypes

ign_datetime         datetime64[ns]
discover_datetime    datetime64[ns]
control_datetime     datetime64[ns]
report_datetime      datetime64[ns]
dtype: object

In [23]:
df["discovery_to_control"] = df["control_datetime"] - df["discover_datetime"]
df["discovery_to_control"]

0       NaT
2       NaT
3       NaT
4       NaT
6       NaT
         ..
23485   NaT
23486   NaT
23487   NaT
23488   NaT
23489   NaT
Name: discovery_to_control, Length: 22092, dtype: timedelta64[ns]

## GroupBy
- `groupby()`
Another method inspired by the SQL command of the same name, `groupby()` allows us to group data based on specific parameters and then perform calculations on those groups.

Think of it like sorting data into buckets based on a column value. Let's say we have data on t-shirts and we group by size. Each row would be placed into a bucket (group) based on the size value.

For example, if we grouped by `size`, all rows with `size = S` would go into one bucket, all rows with `size = M` into another, and all rows with `size = L` into another.

Once the data is organized into these groups, we can perform calculations on each bucket. For instance, we could count how many t-shirts are in each size, calculate the average price per size, or find the total number of shirts sold for each size.

In [48]:
#Smaller data set

small_df = pd.DataFrame({
    "fire_id": [1,2,3,4,5,6,7,8,9,10],
    "fire_year": [2020,2020,2021,2021,2021,2022,2022,2022,2023,2023],
    "estimated_total_acres": [3.2, 10.5, 25.0, 5.5, 40.0, 12.0, 8.4, 60.0, 2.1, 15.0]
})

small_df

   fire_id  fire_year  estimated_total_acres
0        1       2020                    3.2
1        2       2020                   10.5
2        3       2021                   25.0
3        4       2021                    5.5
4        5       2021                   40.0
5        6       2022                   12.0
6        7       2022                    8.4
7        8       2022                   60.0
8        9       2023                    2.1
9       10       2023                   15.0

In [46]:
# GroupBy doesn't act on its own. It is the first step in an aggregation.

small_df.groupby("fire_year")


for year, group in small_df.groupby("fire_year"):
    print(year)
    print(group)

2020
   fire_id  fire_year  estimated_total_acres
0        1       2020                    3.2
1        2       2020                   10.5
2021
   fire_id  fire_year  estimated_total_acres
2        3       2021                   25.0
3        4       2021                    5.5
4        5       2021                   40.0
2022
   fire_id  fire_year  estimated_total_acres
5        6       2022                   12.0
6        7       2022                    8.4
7        8       2022                   60.0
2023
   fire_id  fire_year  estimated_total_acres
8        9       2023                    2.1
9       10       2023                   15.0

In [ ]:
df.groupby("fire_year")

for year, group in df.groupby("fire_year"):
    print(year)
    print(group)

2000
       serial_id fire_category  fire_year area_name         district_name  \
2          58256          STAT       2000       EOA        Central Oregon
3          59312          STAT       2000       EOA      Northeast Oregon
67         58259          STAT       2000       EOA        Central Oregon
68         57958          STAT       2000       EOA  Walker Range - WRFPA
69         57990          STAT       2000       NOA           West Oregon
...          ...           ...        ...       ...                   ...
11333      57786          STAT       2000       SOA      Southwest Oregon
11344      58595          STAT       2000       EOA        Central Oregon
11345      59353          STAT       2000       SOA      Southwest Oregon
11355      57943          STAT       2000       EOA          Klamath-Lake
11358      58485          STAT       2000       NOA           West Oregon

         unit_name full_fire_number        fire_name size_class  \
2         John Day     00-952011-01     Slick Ear #2          B
3        La Grande     00-971024-01          Woodley          C
67        John Day     00-952028-01       Snow Basin          A
68        Crescent     00-991200-01  Cheryl Drive #1          A
69       Philomath     00-551003-01      Deerhaven N          B
...            ...              ...              ...        ...
11333  Grants Pass     00-712277-00   RIVERBANKS # 2          A
11344      Sisters     00-955029-01         LAVA # 1          A
11345      Medford     00-711065-01        Blackwell          A
11355     Lakeview     00-982007-01        Road #127          A
11358       Toledo     00-553006-01     Miller Creek          A

       estimated_total_acres  ...  ign_datetime report_datetime  \
2                       0.75  ...           NaT             NaT
3                      80.00  ...           NaT             NaT
67                      0.01  ...           NaT             NaT
68                      0.00  ...           NaT             NaT
69                      0.75  ...           NaT             NaT
...                      ...  ...           ...             ...
11333                   0.10  ...           NaT             NaT
11344                   0.01  ...           NaT             NaT
11345                   0.25  ...           NaT             NaT
11355                   0.10  ...           NaT             NaT
11358                   0.10  ...           NaT             NaT

      discover_datetime control_datetime              created_at  \
2                   NaT              NaT  07/20/2000 09:13:00 AM
3                   NaT              NaT  08/29/2000 03:59:00 PM
67                  NaT              NaT  07/20/2000 11:11:00 AM
68                  NaT              NaT  07/09/2000 11:03:00 AM
69                  NaT              NaT  07/10/2000 05:02:00 PM
...                 ...              ...                     ...
11333               NaT              NaT  06/30/2000 09:27:00 AM
11344               NaT              NaT  08/03/2000 07:59:00 AM
11345               NaT              NaT  08/31/2000 03:46:00 PM
11355               NaT              NaT  07/08/2000 01:33:00 PM
11358               NaT              NaT  07/30/2000 01:55:00 PM

                  modified_at  district_code unit_code district_fire_number  \
2      11/14/2000 09:16:00 AM             95       952                  011
3      12/21/2000 04:22:00 PM             97       971                  024
67     10/23/2000 09:46:00 AM             95       952                  028
68     07/27/2000 04:37:00 PM             99       991                  200
69     07/11/2000 02:21:00 PM             55       551                  003
...                       ...            ...       ...                  ...
11333  07/04/2000 03:20:00 PM             71       712                  277
11344  10/10/2000 10:16:00 AM             95       955                  029
11345  09/07/2000 05:05:00 PM             71       711                  065
11355  10/20/2000 01:20:00 PM             98       982                  007
11358  08/15/2000 01:22:00 PM             55       553                  006

      discovery_to_control
2                      NaT
3                      NaT
67                     NaT
68                     NaT
69                     NaT
...                    ...
11333                  NaT
11344                  NaT
11345                  NaT
11355                  NaT
11358                  NaT

[912 rows x 38 columns]
2001
       serial_id fire_category  fire_year area_name         district_name  \
4          61657          STAT       2001       SOA      Southwest Oregon
65         61672          STAT       2001       EOA          Klamath-Lake
76         60115          STAT       2001       EOA  Walker Range - WRFPA
82         61117          STAT       2001       SOA      Southwest Oregon
83         62022          STAT       2001       SOA          Western Lane
...          ...           ...        ...       ...                   ...
11357      61815          STAT       2001       EOA          Klamath-Lake
11365      62622          STAT       2001       NOA           West Oregon
11366      60511          STAT       2001       SOA      Southwest Oregon
11367      60425          STAT       2001       EOA        Central Oregon
11374      60974          STAT       2001       NOA          Forest Grove

           unit_name full_fire_number             fire_name size_class  \
4        Grants Pass     01-712133-02         QUEENS BRANCH          A
65          Lakeview     01-982066-02         Campbell #341          B
76          Crescent     01-991262-01           Wildwood #1          A
82       Grants Pass     01-712097-02         HIDDEN VALLEY          A
83            Veneta     01-781026-02     Heceta Beach 0823          A
...              ...              ...                   ...        ...
11357       Lakeview     01-982087-02       Ivory Pine #410          A
11365         Toledo     01-553016-02            1000 Old's          A
11366    Grants Pass     01-712339-01       RAILROAD MP 475          A
11367     The Dalles     01-954067-01             Pond Fire          B
11374  Columbia City     01-532009-02  Stewart Creek Rd. #1          A

       estimated_total_acres  ...  ign_datetime report_datetime  \
4                       0.10  ...           NaT             NaT
65                      0.50  ...           NaT             NaT
76                      0.01  ...           NaT             NaT
82                      0.01  ...           NaT             NaT
83                      0.01  ...           NaT             NaT
...                      ...  ...           ...             ...
11357                   0.25  ...           NaT             NaT
11365                   0.01  ...           NaT             NaT
11366                   0.01  ...           NaT             NaT
11367                   1.00  ...           NaT             NaT
11374                   0.01  ...           NaT             NaT

      discover_datetime control_datetime              created_at  \
4                   NaT              NaT  08/10/2001 06:42:00 PM
65                  NaT              NaT  08/11/2001 07:48:00 AM
76                  NaT              NaT  05/18/2001 11:54:00 AM
82                  NaT              NaT  07/15/2001 03:08:00 PM
83                  NaT              NaT  08/23/2001 12:54:00 PM
...                 ...              ...                     ...
11357               NaT              NaT  08/14/2001 11:01:00 AM
11365               NaT              NaT  09/25/2001 09:45:00 AM
11366               NaT              NaT  06/30/2001 03:09:00 PM
11367               NaT              NaT  06/21/2001 03:41:00 PM
11374               NaT              NaT  07/14/2001 11:14:00 AM

                  modified_at  district_code unit_code district_fire_number  \
4      08/17/2001 11:45:00 AM             71       712                  133
65     08/18/2001 02:34:00 PM             98       982                  066
76     09/12/2004 09:40:00 AM             99       991                  262
82     07/25/2001 12:52:00 PM             71       712                  097
83     09/24/2001 11:12:00 AM             78       781                  026
...                       ...            ...       ...                  ...
11357  09/10/2004 03:06:00 PM             98       982                  087
11365  10/30/2001 11:46:00 AM             55       553                  016
11366  07/04/2001 11:30:00 AM             71       712                  339
11367  07/11/2001 12:46:00 PM             95       954                  067
11374  07/28/2001 04:02:00 PM             53       532                  009

      discovery_to_control
4                      NaT
65                     NaT
76                     NaT
82                     NaT
83                     NaT
...                    ...
11357                  NaT
11365                  NaT
11366                  NaT
11367                  NaT
11374                  NaT

[1270 rows x 38 columns]
2002
       serial_id fire_category  fire_year area_name     district_name  \
6          63735          STAT       2002       NOA       West Oregon
78         63937          STAT       2002       EOA    Central Oregon
88         65848          STAT       2002       SOA    Douglas - DFPA
92         63506          STAT       2002       SOA  Southwest Oregon
101        64277          STAT       2002       SOA  Southwest Oregon
...          ...           ...        ...       ...               ...
11338      64371          STAT       2002       EOA      Klamath-Lake
11351      65457          STAT       2002       SOA      Western Lane
11353      63945          STAT       2002       EOA    Central Oregon
11363      65881          STAT       2002       SOA       Coos - CFPA
11377      64059          STAT       2002       SOA    Douglas - DFPA

         unit_name full_fire_number               fire_name size_class  \
6        Philomath     02-551001-03                    WREN          A
78        John Day     02-952009-03              Fir Hollow          A
88      DFPA South     02-732490-03     Wilbur Cemetery Rd.          B
92     Grants Pass     02-712457-02       1111 CHENEY CREEK          B
101        Medford     02-711069-03                   B6169          A
...            ...              ...                     ...        ...
11338      Klamath     02-981037-03            ECHO SPRINGS          B
11351       Veneta     02-781089-03  Horton Vehicle Fire #2          A
11353     John Day     02-952019-03        Laycock Creek II          B
11363     Coos Bay     02-721033-03         Hungry Mountain          A
11377   DFPA South     02-732332-03        Shively Creek #2          C

       estimated_total_acres  ...  ign_datetime report_datetime  \
6                       0.01  ...           NaT             NaT
78                      0.10  ...           NaT             NaT
88                      0.50  ...           NaT             NaT
92                      1.00  ...           NaT             NaT
101                     0.01  ...           NaT             NaT
...                      ...  ...           ...             ...
11338                   0.60  ...           NaT             NaT
11351                   0.10  ...           NaT             NaT
11353                   5.25  ...           NaT             NaT
11363                   0.25  ...           NaT             NaT
11377                  43.39  ...           NaT             NaT

      discover_datetime control_datetime              created_at  \
6                   NaT              NaT  07/07/2002 09:16:00 AM
78                  NaT              NaT  07/15/2002 01:39:00 AM
88                  NaT              NaT  10/28/2002 09:36:00 AM
92                  NaT              NaT  06/23/2002 01:34:00 PM
101                 NaT              NaT  07/24/2002 06:05:00 PM
...                 ...              ...                     ...
11338               NaT              NaT  07/27/2002 04:55:00 PM
11351               NaT              NaT  09/25/2002 03:54:00 PM
11353               NaT              NaT  07/15/2002 02:32:00 AM
11363               NaT              NaT  10/30/2002 06:47:00 PM
11377               NaT              NaT  07/17/2002 10:25:00 AM

                  modified_at  district_code unit_code district_fire_number  \
6      07/28/2002 10:08:00 AM             55       551                  001
78     01/15/2003 04:47:00 PM             95       952                  009
88     01/16/2003 01:51:00 PM             73       732                  490
92     06/29/2002 10:20:00 AM             71       712                  457
101    07/28/2002 12:47:00 PM             71       711                  069
...                       ...            ...       ...                  ...
11338  04/04/2003 02:27:00 PM             98       981                  037
11351  09/08/2004 02:15:00 PM             78       781                  089
11353  10/29/2002 10:49:00 AM             95       952                  019
11363  11/07/2002 02:47:00 PM             72       721                  033
11377  09/26/2002 01:37:00 PM             73       732                  332

      discovery_to_control
6                      NaT
78                     NaT
88                     NaT
92                     NaT
101                    NaT
...                    ...
11338                  NaT
11351                  NaT
11353                  NaT
11363                  NaT
11377                  NaT

[1168 rows x 38 columns]
2003
       serial_id fire_category  fire_year area_name         district_name  \
7          68019          STAT       2003       NOA           West Oregon
8          68067          STAT       2003       EOA      Northeast Oregon
9          68224          STAT       2003       EOA  Walker Range - WRFPA
94         69095          STAT       2003       SOA      Southwest Oregon
96         68416          STAT       2003       EOA        Central Oregon
...          ...           ...        ...       ...                   ...
11354      68760          STAT       2003       NOA         North Cascade
11356      67154          STAT       2003       EOA  Walker Range - WRFPA
11360      68660          STAT       2003       EOA        Central Oregon
11364      68590          STAT       2003       SOA        Douglas - DFPA
11371      67707          STAT       2003       SOA      Southwest Oregon

         unit_name full_fire_number          fire_name size_class  \
7           Dallas     03-552013-04       Ritner Creek          A
8          Wallowa     03-974016-04       Big Tamarack          A
9         Crescent     03-991228-04          COIDC 918          A
94     Grants Pass     03-712388-04  2300 THOMPSON CK.          A
96      Prineville     03-951025-04          East Fork          A
...            ...              ...                ...        ...
11354      Molalla     03-581078-04    Pine Creek Fire          C
11356     Crescent     03-991286-03       Horse Manure          A
11360   The Dalles     03-954043-04       Riordan Hill          A
11364   DFPA South     03-732126-04           Kingsway          A
11371      Medford     03-711086-04        Buck Prarie          A

       estimated_total_acres  ...  ign_datetime report_datetime  \
7                       0.01  ...           NaT             NaT
8                       0.01  ...           NaT             NaT
9                       0.00  ...           NaT             NaT
94                      0.01  ...           NaT             NaT
96                      0.01  ...           NaT             NaT
...                      ...  ...           ...             ...
11354                  12.40  ...           NaT             NaT
11356                   0.02  ...           NaT             NaT
11360                   0.25  ...           NaT             NaT
11364                   0.20  ...           NaT             NaT
11371                   0.01  ...           NaT             NaT

      discover_datetime control_datetime              created_at  \
7                   NaT              NaT  08/22/2003 04:12:00 PM
8                   NaT              NaT  08/25/2003 02:16:00 PM
9                   NaT              NaT  09/01/2003 03:24:00 PM
94                  NaT              NaT  10/31/2003 08:50:00 AM
96                  NaT              NaT  09/09/2003 08:41:00 AM
...                 ...              ...                     ...
11354               NaT              NaT  09/28/2003 04:18:00 PM
11356               NaT              NaT  07/26/2003 11:26:00 AM
11360               NaT              NaT  09/28/2003 10:18:00 AM
11364               NaT              NaT  09/23/2003 10:04:00 AM
11371               NaT              NaT  08/07/2003 03:13:00 PM

                  modified_at  district_code unit_code district_fire_number  \
7      09/04/2003 09:39:00 AM             55       552                  013
8      09/16/2004 03:07:00 PM             97       974                  016
9      09/12/2003 03:43:00 PM             99       991                  228
94     10/31/2003 09:21:00 AM             71       712                  388
96     10/17/2003 02:13:00 PM             95       951                  025
...                       ...            ...       ...                  ...
11354  07/14/2004 03:26:00 PM             58       581                  078
11356  07/26/2003 01:37:00 PM             99       991                  286
11360  10/16/2003 10:26:00 AM             95       954                  043
11364  10/07/2003 01:29:00 PM             73       732                  126
11371  08/12/2003 04:46:00 PM             71       711                  086

      discovery_to_control
7                      NaT
8                      NaT
9                      NaT
94                     NaT
96                     NaT
...                    ...
11354                  NaT
11356                  NaT
11360                  NaT
11364                  NaT
11371                  NaT

[1161 rows x 38 columns]
2004
       serial_id fire_category  fire_year area_name         district_name  \
71         70870          STAT       2004       EOA          Klamath-Lake
81         70434          STAT       2004       EOA          Klamath-Lake
107        69966          STAT       2004       NOA             Tillamook
112        69794          STAT       2004       EOA          Klamath-Lake
119        70782          STAT       2004       EOA  Walker Range - WRFPA
...          ...           ...        ...       ...                   ...
11269      71049          STAT       2004       SOA      Southwest Oregon
11306      71439          STAT       2004       EOA      Northeast Oregon
11312      70712          STAT       2004       SOA      Southwest Oregon
11342      70341          STAT       2004       SOA           Coos - CFPA
11372      70274          STAT       2004       SOA      Southwest Oregon

         unit_name full_fire_number           fire_name size_class  \
71         Klamath     04-981085-05                SNAG          A
81        Lakeview     04-982024-05             Rimrock          B
107      Tillamook     04-511010-05         POWDERHOUSE          B
112        Klamath     04-981211-04               FINCH          A
119       Crescent     04-991242-05            LIFC 329          A
...            ...              ...                 ...        ...
11269  Grants Pass     04-712142-05  1752 Rounds Avenue          A
11306        Baker     04-972028-05            Two Pile          A
11312  Grants Pass     04-712115-05     340 China Creek          A
11342       Bridge     04-722001-05     Hoffman Wayside          A
11372      Medford     04-711060-05           Grandview          A

       estimated_total_acres  ...  ign_datetime report_datetime  \
71                      0.10  ...           NaT             NaT

# Your Turn!
Find a cleaned dataset **with multiple tables** to work with and call `groupby()` on it using different columns.  
Explore the groups that are created by inspecting them with the `.groups` attribute.

In [47]:
#Numbers of the DF index/row
small_df.groupby("fire_year").groups

{2020: [0, 1], 2021: [2, 3, 4], 2022: [5, 6, 7], 2023: [8, 9]}

In [ ]:
df.groupby("fire_year").groups

{2000: [2, 3, 67, 68, 69, 104, 127, 143, 150, 169, 177, 222, 230, 253, 260, 268, 271, 286, 306, 321, 333, 342, 363, 367, 374, 394, 409, 411, 439, 442, 457, 464, 467, 492, 517, 518, 522, 524, 624, 645, 667, 685, 689, 691, 696, 707, 711, 714, 715, 716, 735, 746, 747, 761, 764, 778, 795, 830, 835, 836, 882, 901, 909, 934, 946, 957, 988, 1004, 1023, 1046, 1047, 1085, 1097, 1099, 1125, 1134, 1141, 1143, 1158, 1159, 1222, 1239, 1245, 1250, 1253, 1254, 1266, 1279, 1325, 1341, 1347, 1378, 1386, 1412, 1437, 1441, 1453, 1456, 1460, 1484, ...], 2001: [4, 65, 76, 82, 83, 86, 99, 111, 113, 117, 122, 138, 140, 148, 154, 155, 158, 181, 184, 185, 188, 197, 202, 214, 216, 225, 227, 237, 251, 270, 284, 288, 293, 308, 318, 319, 320, 338, 350, 377, 384, 387, 390, 397, 401, 404, 417, 419, 423, 435, 440, 451, 461, 477, 478, 484, 489, 491, 493, 520, 521, 535, 543, 572, 575, 580, 591, 602, 619, 623, 628, 629, 648, 655, 668, 687, 692, 697, 703, 706, 709, 721, 728, 732, 736, 759, 769, 777, 783, 784, 794, 796, 797, 804, 805, 807, 817, 823, 838, 860, ...], 2002: [6, 78, 88, 92, 101, 135, 147, 153, 159, 160, 163, 167, 175, 178, 180, 198, 218, 242, 248, 250, 261, 279, 301, 304, 309, 311, 312, 323, 334, 355, 398, 405, 414, 415, 436, 462, 463, 472, 479, 487, 499, 527, 528, 541, 550, 555, 556, 557, 567, 579, 581, 597, 600, 603, 604, 609, 614, 615, 627, 633, 640, 651, 654, 674, 686, 695, 705, 718, 731, 780, 798, 809, 843, 854, 864, 865, 883, 888, 891, 895, 907, 912, 916, 920, 938, 949, 960, 963, 964, 980, 987, 1016, 1018, 1029, 1035, 1042, 1059, 1065, 1069, 1084, ...], 2003: [7, 8, 9, 94, 96, 100, 109, 110, 121, 129, 136, 164, 165, 170, 172, 204, 210, 213, 215, 220, 221, 224, 231, 233, 241, 258, 263, 266, 267, 269, 281, 289, 294, 299, 313, 326, 328, 343, 365, 410, 418, 426, 427, 445, 452, 459, 468, 503, 507, 515, 519, 536, 540, 542, 548, 552, 554, 573, 582, 585, 607, 621, 631, 639, 657, 681, 712, 717, 730, 742, 770, 781, 785, 790, 792, 810, 815, 821, 828, 829, 837, 846, 855, 858, 894, 896, 897, 900, 902, 919, 932, 935, 936, 951, 991, 995, 1000, 1002, 1009, 1024, ...], 2004: [71, 81, 107, 112, 119, 125, 130, 144, 149, 162, 182, 187, 189, 203, 205, 223, 232, 256, 275, 291, 324, 356, 369, 371, 375, 391, 392, 402, 422, 429, 433, 456, 490, 494, 502, 559, 564, 576, 586, 618, 630, 635, 660, 662, 679, 683, 694, 698, 704, 713, 729, 738, 745, 753, 754, 768, 773, 801, 806, 820, 827, 839, 859, 870, 886, 889, 903, 906, 910, 973, 977, 978, 984, 1001, 1010, 1013, 1017, 1044, 1054, 1075, 1105, 1113, 1116, 1123, 1133, 1164, 1179, 1192, 1204, 1232, 1258, 1262, 1267, 1273, 1294, 1304, 1312, 1322, 1349, 1362, ...], 2005: [10, 11, 72, 74, 84, 85, 93, 116, 137, 139, 171, 183, 196, 238, 257, 276, 302, 303, 325, 327, 331, 336, 337, 353, 357, 361, 381, 388, 428, 434, 443, 444, 455, 486, 514, 516, 530, 544, 545, 565, 570, 584, 598, 637, 649, 658, 699, 727, 743, 744, 755, 765, 775, 782, 786, 789, 800, 802, 811, 812, 852, 863, 879, 890, 892, 929, 962, 990, 1011, 1015, 1026, 1038, 1072, 1076, 1078, 1083, 1126, 1152, 1162, 1182, 1193, 1194, 1213, 1215, 1226, 1235, 1256, 1277, 1282, 1299, 1300, 1301, 1305, 1313, 1348, 1355, 1356, 1387, 1390, 1401, ...], 2006: [73, 89, 105, 118, 123, 126, 132, 134, 141, 151, 152, 193, 195, 209, 211, 219, 226, 239, 274, 290, 292, 300, 305, 332, 335, 339, 345, 346, 347, 352, 370, 372, 373, 380, 385, 393, 400, 412, 430, 446, 448, 449, 469, 470, 481, 496, 497, 504, 505, 506, 510, 512, 525, 533, 537, 538, 551, 561, 562, 563, 592, 593, 599, 610, 625, 632, 638, 652, 663, 664, 665, 670, 675, 677, 680, 700, 702, 719, 726, 750, 751, 756, 771, 772, 799, 808, 822, 832, 844, 849, 850, 861, 866, 876, 885, 887, 908, 914, 915, 926, ...], 2007: [12, 66, 77, 79, 98, 128, 142, 161, 186, 190, 192, 199, 200, 206, 207, 243, 245, 246, 252, 264, 273, 278, 280, 282, 295, 307, 315, 317, 322, 348, 354, 359, 362, 364, 376, 379, 395, 396, 403, 438, 441, 450, 454, 460, 473, 474, 475, 483, 485, 488, 501, 508, 509, 558, 566, 577, 590, 611, 620, 626, 634, 647, 650, 661, 673, 678, 693, 710, 723, 733, 749, 763, 787, 791, 793, 819, 824, 826, 834, 847, 853, 857, 868, 872, 874, 875, 877, 899, 918, 925, 927, 931, 941, 947, 953, 955, 956, 981, 983, 985, ...], 2008: [15, 16, 75, 91, 103, 106, 120, 133, 145, 166, 168, 173, 208, 234, 235, 247, 255, 262, 285, 296, 341, 344, 351, 360, 378, 382, 386, 406, 407, 424, 431, 453, 458, 476, 482, 526, 529, 531, 539, 546, 553, 568, 583, 587, 596, 606, 608, 612, 613, 617, 622, 643, 659, 669, 682, 701, 722, 725, 737, 741, 752, 757, 760, 766, 767, 774, 776, 788, 803, 813, 816, 825, 841, 842, 848, 862, 871, 911, 922, 924, 928, 943, 952, 959, 965, 994, 1005, 1008, 1028, 1033, 1056, 1070, 1074, 1095, 1096, 1100, 1120, 1124, 1128, 1138, ...], 2009: [18, 19, 21, 22, 70, 87, 90, 95, 114, 124, 131, 146, 157, 174, 176, 191, 217, 228, 229, 236, 240, 244, 265, 277, 283, 287, 297, 298, 314, 329, 330, 340, 349, 383, 389, 399, 413, 421, 425, 432, 466, 471, 480, 495, 500, 511, 513, 523, 549, 560, 571, 578, 589, 594, 595, 605, 636, 641, 642, 644, 646, 656, 671, 672, 676, 688, 720, 724, 734, 739, 740, 758, 762, 814, 818, 831, 833, 851, 867, 873, 880, 893, 898, 904, 905, 913, 917, 948, 954, 968, 971, 997, 1003, 1012, 1025, 1037, 1050, 1062, 1064, 1094, ...], 2010: [24, 25, 26, 27, 201, 212, 254, 259, 272, 358, 366, 368, 416, 420, 437, 447, 498, 532, 534, 588, 601, 666, 779, 845, 856, 878, 923, 940, 961, 969, 976, 1021, 1031, 1063, 1087, 1102, 1144, 1150, 1221, 1261, 1311, 1389, 1413, 1506, 1550, 1565, 1570, 1577, 1617, 1621, 1625, 1685, 1687, 1689, 1748, 1793, 1818, 1826, 1870, 1875, 1879, 1886, 1921, 1954, 1962, 1965, 1985, 2094, 2143, 2174, 2216, 2271, 2321, 2365, 2392, 2402, 2482, 2489, 2517, 2525, 2526, 2538, 2539, 2590, 2631, 2635, 2729, 2765, 2818, 2892, 2921, 2975, 2982, 3020, 3054, 3066, 3098, 3116, 3195, 3214, ...], 2011: [28, 11381, 11382, 11417, 11438, 11450, 11456, 11481, 11532, 11561, 11574, 11592, 11610, 11623, 11625, 11642, 11666, 11670, 11712, 11714, 11738, 11739, 11755, 11762, 11765, 11776, 11814, 11815, 11895, 11939, 11977, 11981, 11999, 12002, 12005, 12007, 12026, 12038, 12055, 12070, 12122, 12172, 12191, 12223, 12233, 12272, 12287, 12305, 12327, 12328, 12345, 12375, 12388, 12412, 12421, 12434, 12515, 12521, 12528, 12530, 12540, 12541, 12620, 12651, 12708, 12724, 12731, 12778, 12831, 12846, 12865, 12874, 12917, 12924, 12925, 12933, 12935, 12939, 12943, 12993, 12994, 13035, 13043, 13044, 13069, 13074, 13078, 13090, 13091, 13151, 13152, 13183, 13196, 13202, 13208, 13214, 13285, 13415, 13417, 13427, ...], 2012: [11395, 11396, 11399, 11410, 11412, 11426, 11434, 11452, 11461, 11468, 11471, 11497, 11508, 11535, 11536, 11559, 11577, 11598, 11622, 11654, 11686, 11699, 11703, 11706, 11711, 11722, 11749, 11759, 11787, 11789, 11817, 11830, 11870, 11885, 11913, 11917, 11922, 11947, 11979, 11989, 11998, 12000, 12022, 12027, 12050, 12060, 12074, 12075, 12085, 12088, 12099, 12109, 12115, 12130, 12150, 12171, 12229, 12255, 12275, 12289, 12304, 12322, 12337, 12355, 12376, 12386, 12387, 12395, 12420, 12426, 12479, 12484, 12504, 12507, 12516, 12546, 12558, 12571, 12576, 12589, 12590, 12593, 12611, 12624, 12664, 12666, 12668, 12679, 12680, 12681, 12685, 12725, 12729, 12747, 12758, 12789, 12819, 12822, 12893, 12908, ...], 2013: [10100, 10306, 11379, 11390, 11401, 11405, 11414, 11424, 11428, 11429, 11447, 11454, 11460, 11466, 11472, 11487, 11490, 11493, 11496, 11510, 11513, 11524, 11526, 11528, 11556, 11558, 11585, 11590, 11593, 11605, 11608, 11612, 11613, 11615, 11616, 11624, 11627, 11638, 11659, 11679, 11689, 11692, 11700, 11717, 11718, 11720, 11725, 11735, 11760, 11761, 11775, 11777, 11782, 11791, 11818, 11824, 11825, 11836, 11846, 11851, 11853, 11862, 11867, 11874, 11875, 11896, 11909, 11923, 11927, 11945, 11949, 11984, 11987, 11995, 12008, 12011, 12018, 12021, 12087, 12097, 12154, 12155, 12174, 12201, 12222, 12226, 12231, 12236, 12246, 12257, 12270, 12271, 12299, 12301, 12303, 12309, 12312, 12316, 12321, 12338, ...], 2014: [13, 33, 34, 11392, 11407, 11423, 11433, 11440, 11475, 11479, 11482, 11492, 11521, 11525, 11530, 11534, 11540, 11549, 11550, 11567, 11572, 11573, 11576, 11587, 11594, 11599, 11603, 11632, 11647, 11668, 11707, 11721, 11727, 11736, 11744, 11750, 11763, 11770, 11785, 11796, 11831, 11837, 11844, 11850, 11852, 11864, 11868, 11876, 11891, 11894, 11897, 11902, 11908, 11915, 11921, 11925, 11933, 11934, 11951, 11967, 11978, 12020, 12083, 12089, 12101, 12102, 12113, 12121, 12135, 12137, 12145, 12146, 12173, 12178, 12181, 12184, 12185, 12187, 12190, 12192, 12196, 12204, 12208, 12227, 12249, 12250, 12274, 12283, 12292, 12311, 12313, 12320, 12323, 12330, 12335, 12347, 12369, 12389, 12390, 12405, ...], 2015: [0, 35, 36, 37, 38, 10358, 11409, 11413, 11420, 11422, 11457, 11462, 11474, 11476, 11477, 11484, 11494, 11499, 11515, 11523, 11531, 11533, 11542, 11565, 11569, 11596, 11660, 11672, 11677, 11693, 11713, 11729, 11757, 11766, 11800, 11804, 11812, 11816, 11835, 11848, 11859, 11871, 11900, 11924, 11929, 11972, 11975, 11991, 12003, 12019, 12029, 12033, 12036, 12059, 12062, 12065, 12072, 12076, 12081, 12090, 12107, 12112, 12119, 12120, 12148, 12160, 12176, 12179, 12195, 12199, 12207, 12221, 12224, 12225, 12262, 12278, 12284, 12285, 12293, 12296, 12326, 12334, 12368, 12394, 12411, 12429, 12439, 12448, 12466, 12500, 12513, 12518, 12538, 12542, 12569, 12570, 12578, 12597, 12608, 12609, ...], 2016: [40, 41, 42, 43, 10461, 11385, 11388, 11394, 11397, 11398, 11425, 11431, 11437, 11441, 11445, 11451, 11483, 11501, 11507, 11514, 11516, 11563, 11581, 11606, 11607, 11628, 11641, 11690, 11694, 11724, 11733, 11742, 11788, 11792, 11799, 11811, 11813, 11841, 11855, 11860, 11881, 11912, 11931, 11943, 11952, 11954, 11986, 11990, 11996, 12004, 12017, 12023, 12035, 12044, 12045, 12056, 12080, 12093, 12094, 12098, 12131, 12143, 12153, 12169, 12182, 12209, 12258, 12261, 12268, 12273, 12298, 12300, 12308, 12325, 12350, 12353, 12357, 12362, 12391, 12401, 12455, 12458, 12468, 12480, 12491, 12508, 12533, 12535, 12548, 12557, 12573, 12579, 12587, 12596, 12628, 12652, 12660, 12691, 12700, 12701, ...], 2017: [44, 45, 46, 47, 48, 11406, 11430, 11443, 11449, 11464, 11465, 11505, 11509, 11520, 11529, 11546, 11564, 11582, 11604, 11609, 11614, 11629, 11631, 11635, 11636, 11639, 11640, 11643, 11649, 11650, 11657, 11658, 11664, 11673, 11674, 11683, 11687, 11695, 11728, 11734, 11743, 11745, 11747, 11753, 11767, 11784, 11802, 11822, 11827, 11829, 11839, 11840, 11847, 11858, 11869, 11878, 11887, 11892, 11893, 11919, 11926, 11932, 11946, 11957, 11959, 11968, 11973, 11976, 11994, 12034, 12041, 12063, 12064, 12067, 12073, 12077, 12092, 12100, 12103, 12114, 12124, 12136, 12141, 12156, 12177, 12180, 12203, 12218, 12248, 12253, 12260, 12266, 12276, 12281, 12290, 12294, 12329, 12332, 12339, 12351, ...], 2018: [49, 50, 51, 53, 11387, 11391, 11402, 11418, 11435, 11453, 11498, 11504, 11506, 11512, 11518, 11522, 11551, 11553, 11560, 11579, 11580, 11586, 11597, 11619, 11651, 11675, 11682, 11697, 11698, 11702, 11730, 11740, 11746, 11758, 11768, 11771, 11779, 11781, 11783, 11786, 11794, 11798, 11801, 11803, 11807, 11809, 11832, 11854, 11861, 11886, 11903, 11928, 11944, 11958, 11963, 11970, 11992, 12001, 12009, 12013, 12016, 12042, 12047, 12078, 12082, 12118, 12140, 12147, 12151, 12165, 12166, 12167, 12175, 12197, 12213, 12214, 12216, 12232, 12259, 12263, 12269, 12282, 12302, 12315, 12324, 12340, 12344, 12346, 12361, 12367, 12379, 12399, 12410, 12413, 12417, 12422, 12427, 12431, 12462, 12471, ...], 2019: [54, 56, 11380, 11393, 11404, 11411, 11415, 11455, 11491, 11502, 11511, 11517, 11554, 11557, 11570, 11584, 11588, 11620, 11621, 11626, 11652, 11662, 11665, 11667, 11678, 11680, 11681, 11705, 11710, 11737, 11748, 11751, 11773, 11805, 11806, 11843, 11872, 11884, 11904, 11906, 11914, 11920, 11941, 11955, 11966, 11971, 11982, 11985, 12012, 12024, 12028, 12043, 12048, 12054, 12061, 12084, 12111, 12116, 12126, 12132, 12138, 12144, 12152, 12158, 12162, 12164, 12189, 12206, 12211, 12212, 12217, 12220, 12228, 12234, 12239, 12241, 12242, 12265, 12267, 12297, 12310, 12317, 12333, 12349, 12359, 12372, 12397, 12409, 12424, 12436, 12453, 12483, 12494, 12510, 12522, 12525, 12544, 12549, 12556, 12580, ...], 2020: [57, 58, 11389, 11400, 11416, 11444, 11458, 11478, 11480, 11485, 11519, 11543, 11544, 11555, 11568, 11589, 11591, 11600, 11633, 11648, 11655, 11656, 11684, 11688, 11708, 11709, 11731, 11756, 11774, 11780, 11823, 11826, 11828, 11834, 11842, 11849, 11863, 11877, 11882, 11890, 11899, 11901, 11916, 11935, 11937, 11940, 11953, 11962, 11974, 11993, 12015, 12030, 12032, 12039, 12051, 12057, 12058, 12066, 12105, 12108, 12117, 12133, 12134, 12139, 12161, 12170, 12194, 12238, 12244, 12245, 12251, 12277, 12288, 12314, 12356, 12374, 12378, 12398, 12400, 12402, 12406, 12416, 12418, 12425, 12450, 12481, 12485, 12493, 12529, 12547, 12555, 12559, 12567, 12568, 12591, 12602, 12606, 12642, 12663, 12669, ...], 2021: [63, 11384, 11408, 11427, 11436, 11442, 11459, 11469, 11470, 11486, 11488, 11527, 11537, 11538, 11545, 11548, 11552, 11571, 11583, 11601, 11602, 11618, 11644, 11653, 11669, 11671, 11685, 11691, 11701, 11716, 11719, 11726, 11732, 11764, 11769, 11778, 11793, 11797, 11808, 11810, 11820, 11845, 11856, 11866, 11873, 11879, 11883, 11888, 11889, 11898, 11907, 11930, 11936, 11938, 11950, 11964, 11965, 11969, 12010, 12025, 12031, 12049, 12053, 12106, 12110, 12123, 12125, 12142, 12168, 12183, 12188, 12193, 12202, 12205, 12215, 12235, 12240, 12247, 12254, 12256, 12280, 12295, 12318, 12341, 12373, 12380, 12382, 12396, 12408, 12414, 12430, 12438, 12443, 12445, 12446, 12472, 12498, 12503, 12505, 12509, ...], 2022: [64, 22296, 22329, 22373, 22374, 22378, 22379, 22380, 22383, 22384, 22385, 22386, 22387, 22388, 22389, 22390, 22391, 22392, 22393, 22394, 22395, 22396, 22398, 22400, 22401, 22402, 22404, 22405, 22406, 22407, 22408, 22410, 22411, 22412, 22414, 22415, 22417, 22418, 22419, 22420, 22421, 22422, 22424, 22425, 22427, 22428, 22429, 22430, 22431, 22432, 22433, 22434, 22435, 22437, 22438, 22439, 22441, 22442, 22443, 22445, 22446, 22448, 22450, 22451, 22452, 22453, 22456, 22457, 22458, 22459, 22461, 22462, 22464, 22465, 22466, 22468, 22470, 22471, 22472, 22473, 22475, 22476, 22477, 22478, 22479, 22480, 22481, 22484, 22485, 22486, 22488, 22489, 22491, 22493, 22495, 22496, 22498, 22499, 22500, 22502, ...]}

In [49]:
small_df.groupby("fire_year").count()

           fire_id  estimated_total_acres
fire_year
2020             2                      2
2021             3                      3
2022             3                      3
2023             2                      2

In [ ]:
# GroupBy doesn't act on its own. It is the first step in an aggregation.
df.groupby("fire_year")

# When paired with something like the count() method,
# Pandas finds all rows with the same fire_year,
# groups them together, and returns the total count for each column.
# However, the result looks a bit off...
df.groupby("fire_year").count()

,serial_id,fire_category,area_name,district_name,unit_name,full_fire_number,fire_name,size_class,estimated_total_acres,protected_acres,...,ign_datetime,report_datetime,discover_datetime,control_datetime,created_at,modified_at,district_code,unit_code,district_fire_number,discovery_to_control
fire_year,,,,,,,,,,,,,,,,,,,,,
2000,912,912,912,912,912,912,912,912,912,912,...,0,0,0,0,912,912,912,912,912,0
2001,1270,1270,1270,1270,1270,1270,1270,1270,1270,1270,...,0,0,0,0,1270,1270,1270,1270,1270,0
2002,1168,1168,1168,1168,1168,1168,1168,1168,1168,1168,...,0,0,0,0,1168,1168,1168,1168,1168,0
2003,1161,1161,1161,1161,1161,1161,1161,1161,1161,1161,...,0,0,0,0,1161,1161,1161,1161,1161,0
2004,914,914,914,914,914,914,914,914,914,914,...,0,0,0,0,914,914,914,914,914,0
2005,822,822,822,822,822,822,822,822,822,822,...,0,0,0,0,822,822,822,822,822,0
2006,1312,1312,1312,1312,1312,1312,1312,1312,1312,1312,...,0,0,0,0,1312,1312,1312,1312,1312,0
2007,1197,1197,1197,1197,1197,1197,1197,1197,1197,1197,...,0,0,0,0,1197,1197,1197,1197,1197,0
2008,1006,1006,1006,1006,1006,1006,1006,1006,1006,1006,...,0,0,0,0,1006,1006,1006,1006,1006,0
2009,934,934,934,934,934,934,934,934,934,934,...,0,0,0,0,934,934,934,934,934,0
2010,633,633,633,633,633,633,633,633,633,633,...,0,0,0,0,633,633,633,633,633,0
2011,637,637,637,637,637,637,637,637,637,637,...,0,0,0,0,637,637,637,637,637,0
2012,653,653,653,653,653,653,653,653,653,653,...,0,0,0,0,653,653,653,653,653,0
2013,1102,1102,1102,1102,1102,1102,1102,1102,1102,1102,...,0,0,0,0,1102,1102,1102,1102,1102,0
2014,1048,1048,1048,1048,1048,1048,1048,1048,1048,1048,...,0,0,0,0,1048,1048,1048,1048,1048,0
2015,970,970,970,970,970,970,970,970,970,970,...,0,0,0,0,970,970,970,970,970,0
2016,762,762,762,762,762,762,762,762,762,762,...,0,0,0,0,762,762,762,762,762,0
2017,1003,1003,1003,1003,1003,1003,1003,1003,1003,1003,...,0,0,0,0,1003,1003,1003,1003,1003,0
2018,999,999,999,999,999,999,999,999,999,999,...,0,0,0,0,999,999,999,999,999,0
2019,915,915,915,915,915,915,915,915,915,915,...,0,0,0,0,915,915,915,915,915,0
2020,891,891,891,891,891,891,891,891,891,891,...,0,0,0,0,891,891,891,891,891,0
2021,1004,1004,1004,1004,1004,1004,1004,1004,1004,1004,...,0,0,0,0,1004,1004,1004,1004,1004,0
2022,779,779,779,779,779,779,779,779,779,779,...,0,0,0,0,779,779,779,779,779,0

In [83]:
# We will select the ID column and count it to get the total number of fires
df.groupby("fire_year")["serial_id"].count().reset_index(name="total_fires")

    fire_year  total_fires
0        2000          912
1        2001         1270
2        2002         1168
3        2003         1161
4        2004          914
5        2005          822
6        2006         1312
7        2007         1197
8        2008         1006
9        2009          934
10       2010          633
11       2011          637
12       2012          653
13       2013         1102
14       2014         1048
15       2015          970
16       2016          762
17       2017         1003
18       2018          999
19       2019          915
20       2020          891
21       2021         1004
22       2022          779

# Your Turn: GroupBy Count and Sum

Use `groupby()` to group your dataset by a column, then use `count()` to find the number of values in each group.

Next, group by a column and use `sum()` to calculate the total of the values in each group.

In [39]:
# Let's say we want to know the total acres burned per year.
# We would group by fire_year and then select estimated_total_acres.
# Under the hood, this organizes all estimated_total_acres values into groups
# based on the year of the fire.
# sum() tells Pandas to add the values in each group together.

df.groupby("fire_year")["estimated_total_acres"].sum()

fire_year
2000     113334.34
2001      75839.20
2002    1258496.32
2003     123390.00
2004       6413.83
2005      71253.29
2006     120377.14
2007     371144.19
2008      15864.91
2009      65628.52
2010      17922.06
2011      17790.60
2012     220734.28
2013     104521.57
2014     185036.44
2015     315531.98
2016       8529.96
2017     492789.99
2018     236649.90
2019      16977.81
2020     808638.11
2021     531756.94
2022      37358.74
Name: estimated_total_acres, dtype: float64

## Aggregate Methods

The methods we've been using are **aggregation methods**. We've used them before, but not yet in combination with `groupby()`.

To review, some common aggregation methods include:

- `sum()` – total values  
- `mean()` – average values  
- `count()` – number of rows  
- `nunique()` – number of unique values  
- `min()` – smallest value  
- `max()` – largest value

In [59]:
df.groupby("fire_year")["estimated_total_acres"].mean()

fire_year
2000     124.270110
2001      59.715906
2002    1077.479726
2003     106.279070
2004       7.017319
2005      86.682835
2006      91.750869
2007     310.061980
2008      15.770288
2009      70.266081
2010      28.312891
2011      27.928728
2012     338.031057
2013      94.847160
2014     176.561489
2015     325.290701
2016      11.194173
2017     491.316042
2018     236.886787
2019      18.554984
2020     907.562413
2021     529.638386
2022      47.957304
Name: estimated_total_acres, dtype: float64

In [ ]:
# df.groupby("fire_year")["estimated_total_acres"].min()
df[df["estimated_total_acres"] > 1].groupby("fire_year")["estimated_total_acres"].min()

fire_year
2000    1.25
2001    1.10
2002    1.20
2003    1.20
2004    1.10
2005    1.10
2006    1.01
2007    1.01
2008    1.10
2009    1.01
2010    1.13
2011    1.10
2012    1.06
2013    1.10
2014    1.07
2015    1.05
2016    1.01
2017    1.06
2018    1.01
2019    1.01
2020    1.04
2021    1.01
2022    1.04
Name: estimated_total_acres, dtype: float64

In [62]:
df.groupby("fire_year")["estimated_total_acres"].max()

fire_year
2000     56319.00
2001     32352.00
2002    499945.00
2003     90376.00
2004      4705.00
2005     42700.00
2006     53523.45
2007    140360.00
2008      4891.10
2009     16600.00
2010      7494.00
2011      8350.00
2012     93071.00
2013     26725.00
2014     36185.00
2015    101028.00
2016      3424.00
2017    190590.00
2018     58753.00
2019     13119.00
2020    193566.00
2021    413744.00
2022     21347.00
Name: estimated_total_acres, dtype: float64

In [57]:
df.groupby("fire_year")["size_class"].nunique()

fire_year
2000    7
2001    7
2002    7
2003    7
2004    6
2005    7
2006    7
2007    7
2008    6
2009    7
2010    7
2011    6
2012    7
2013    7
2014    7
2015    7
2016    6
2017    7
2018    7
2019    7
2020    7
2021    7
2022    6
Name: size_class, dtype: int64

In [58]:
annual_fire_summary = df[['fire_year', 'fire_name', 'district_name', 'unit_name']].groupby(['fire_year']).nunique()

annual_fire_summary

           fire_name  district_name  unit_name
fire_year
2000             904             14         30
2001            1249             14         30
2002            1151             14         30
2003            1148             14         30
2004             904             14         30
2005             814             14         31
2006            1304             14         31
2007            1179             14         31
2008             996             14         31
2009             931             14         31
2010             625             14         31
2011             633             14         31
2012             651             14         31
2013            1078             14         31
2014            1038             14         31
2015             956             14         31
2016             757             14         29
2017             992             14         31
2018             990             14         30
2019             898             14         31
2020             884             14         30
2021             987             14         30
2022             773             13         30

In [115]:
df.groupby("fire_year")["estimated_total_acres"].agg(["sum", "mean", "max", "min"])

                  sum         mean        max  min
fire_year
2000        113334.34   124.270110   56319.00  0.0
2001         75839.20    59.715906   32352.00  0.0
2002       1258496.32  1077.479726  499945.00  0.0
2003        123390.00   106.279070   90376.00  0.0
2004          6413.83     7.017319    4705.00  0.0
2005         71253.29    86.682835   42700.00  0.0
2006        120377.14    91.750869   53523.45  0.0
2007        371144.19   310.061980  140360.00  0.0
2008         15864.91    15.770288    4891.10  0.0
2009         65628.52    70.266081   16600.00  0.0
2010         17922.06    28.312891    7494.00  0.0
2011         17790.60    27.928728    8350.00  0.0
2012        220734.28   338.031057   93071.00  0.0
2013        104521.57    94.847160   26725.00  0.0
2014        185036.44   176.561489   36185.00  0.0
2015        315531.98   325.290701  101028.00  0.0
2016          8529.96    11.194173    3424.00  0.0
2017        492789.99   491.316042  190590.00  0.0
2018        236649.90   236.886787   58753.00  0.0
2019         16977.81    18.554984   13119.00  0.0
2020        808638.11   907.562413  193566.00  0.0
2021        531756.94   529.638386  413744.00  0.0
2022         37358.74    47.957304   21347.00  0.0

In [117]:
df.groupby(["fire_year", "district_name"])["estimated_total_acres"].sum()

fire_year  district_name
2000       Astoria                 9.18
           Central Oregon       9353.87
           Coos - CFPA            25.20
           Douglas - DFPA        239.47
           Forest Grove           35.97
                                 ...
2022       South Cascade           4.20
           Southwest Oregon    21722.89
           Tillamook               0.08
           West Oregon            42.21
           Western Lane           10.72
Name: estimated_total_acres, Length: 321, dtype: float64

# Your Turn: More GroupBy Aggregations

Use `groupby()` to group your dataset by a column and explore additional aggregation methods.

Try the following:

- Use `mean()` to calculate the average value in each group.
- Use `nunique()` to count the number of unique values in each group.
- Use `min()` to find the smallest value in each group.
- Use `max()` to find the largest value in each group.

Experiment with grouping by different columns and see how the results change.

# Joins, Groups and Aggrigates With lego!

In [76]:

sets = pd.read_csv("sets.csv")
inventories = pd.read_csv("inventories.csv")
inventory_parts = pd.read_csv("inventory_parts.csv")
colors = pd.read_csv("colors.csv")
parts = pd.read_csv("parts.csv")
sets = pd.read_csv("sets.csv")
themes = pd.read_csv("themes.csv")
part_categories = pd.read_csv("part_categories.csv")

In [ ]:
#Sets released a year 
sets.groupby("year")["set_num"].count().reset_index(name="total_sets")

    year  total_sets
0   1950           7
1   1953           4
2   1954          14
3   1955          28
4   1956          12
..   ...         ...
61  2013         593
62  2014         713
63  2015         665
64  2016         596
65  2017         296

[66 rows x 2 columns]

In [89]:
# Merge inventory_parts with colors. The primary key is id in colors and the foreign key is color_id in inventory_parts.
# Then group by the color name, select the quantity column, and sum it to get the total number of parts for each color.
inventory_parts.merge(colors, left_on="color_id", right_on="id").groupby("name")["quantity"].sum()

name
Aqua                  213
Black              396589
Blue               117430
Blue-Violet           197
Bright Green         3916
                    ...
Violet                111
White              221570
Yellow             120440
Yellowish Green       560
[No Color]           2359
Name: quantity, Length: 131, dtype: int64

In [ ]:
#Number of parts in specific catagories 
parts.merge(part_categories, left_on="part_cat_id", right_on="id").groupby("name_y")["part_num"].count().reset_index(name="total_parts")

                                          name_y  total_parts
0                       Bars, Ladders and Fences          115
1                                     Baseplates          250
2                   Belville, Scala and Fabuland          234
3        Bionicle, Hero Factory and Constraction         1116
4                                         Bricks           93
5                                  Bricks Curved          275
6                                 Bricks Printed          744
7                         Bricks Round and Cones          219
8                                  Bricks Sloped          410
9                                 Bricks Special          116
10                                 Bricks Wedged          198
11                                       Clikits          278
12                                    Containers          129
13                       Duplo, Quatro and Primo         1552
14              Flags, Signs, Plastics and Cloth          428
15                                      HO Scale           23
16                   Hinges, Arms and Turntables          162
17                           Magnets and Holders           36
18                                    Mechanical           28
19                           Minifig Accessories         2071
20                                      Minifigs         8556
21  Non-Buildable Figures (Duplo, Fabuland, etc)          109
22                                      Non-LEGO         1964
23                                         Other         1125
24                                        Panels          205
25                            Plants and Animals          742
26                                        Plates           62
27                                 Plates Angled           57
28                       Plates Round and Dishes          146
29                                Plates Special          169
30                                    Pneumatics           28
31      Power Functions, Mindstorms and Electric          462
32                                          Rock           35
33                       String, Bands and Reels           86
34                  Supports, Girders and Cranes           80
35                                 Technic Axles           28
36                                 Technic Beams           32
37                         Technic Beams Special           22
38                                Technic Bricks           26
39                                Technic Bushes            9
40                            Technic Connectors           93
41                                 Technic Gears           68
42                                Technic Panels           56
43                                  Technic Pins           19
44                               Technic Special          158
45       Technic Steering, Suspension and Engine           77
46                                         Tiles           30
47                                 Tiles Printed         1191
48                                 Tiles Special          136
49                                         Tools            8
50                         Transportation - Land          409
51                  Transportation - Sea and Air          206
52                               Tubes and Hoses          157
53                              Wheels and Tyres          270
54                             Windows and Doors          405
55                      Windscreens and Fuselage          268
56                                          Znap           22

In [103]:
sets.merge(inventories, on="set_num", how="inner")[["set_num", "name", "num_parts"]]

,set_num,name,num_parts
0,00-1,Weetabix Castle,471
1,0011-2,Town Mini-Figures,12
2,0011-3,Castle 2 for 1 Bonus Offer,2
3,0012-1,Space Mini-Figures,12
4,0013-1,Space Mini-Figures,12
...,...,...,...
11676,Wauwatosa-1,"LEGO Store Grand Opening Exclusive Set, Mayfai...",15
11677,WHITEHOUSE-1,Micro White House,59
11678,Wiesbaden-1,"LEGO Store Grand Opening Exclusive Set, Wiesba...",146
11679,WishingWell-1,Wishing Well [Toys R Us Promo],28
11680,wwgp1-1,Wild West Limited Edition Gift Pack,3

# Your Turn: Merge, GroupBy, and Aggregate

Merge two tables from your dataset.

Then:

1. Group the merged table by a column.
2. Apply an aggregation method to summarize the grouped data.

Try using methods like:

- `sum()`
- `mean()`
- `count()`
- `max()`
- `min()`